package principal;

import about.About;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics2D;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import splas.Splash;

/**
 *
 * @author Rojeru San
 */
public class GenCodQR extends javax.swing.JFrame {

    private File file;

    /**
     * Creates new form Reproductor
     */
    public GenCodQR() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoCod.png")).getImage());
        this.setLocationRelativeTo(null);
        this.primario.setCursor(new Cursor(12));
        this.secundario.setCursor(new Cursor(12));

    }//end: constructor
    Splash inicio;

    public GenCodQR(Splash inicio) {
        this.inicio = inicio;
        setProgress(0);
        initComponents();
        setProgress(20);
        setProgress(40);
        setProgress(60);
        setProgress(80);
        setProgress(90);
        setProgress(100);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoCod.png")).getImage());
        this.setLocationRelativeTo(null);
        this.primario.setCursor(new Cursor(12));
        this.secundario.setCursor(new Cursor(12));

    }//end: constructor

    void setProgress(int percent) {
        inicio.getJProgressBar().setValue(percent);

        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo ejecutar la presentación");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        panel2 = new org.edisoncor.gui.panel.Panel();
        jLabel2 = new javax.swing.JLabel();
        hora = new org.edisoncor.gui.label.LabelMetric();
        codigo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnGua = new javax.swing.JButton();
        btnGen1 = new javax.swing.JButton();
        btnGen2 = new javax.swing.JButton();
        primario = new org.edisoncor.gui.button.ButtonSeven();
        secundario = new org.edisoncor.gui.button.ButtonSeven();
        hora1 = new org.edisoncor.gui.label.LabelMetric();
        texto = new javax.swing.JTextField();
        cerrar = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 5));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        panel1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N

        panel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barra.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/about.png"))); // NOI18N
        jLabel2.setToolTipText("RojeruSan");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hora.setText("HORA");
        hora.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setOpaque(false);

        btnGua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnGua1.png"))); // NOI18N
        btnGua.setText("Guardar Código");
        btnGua.setToolTipText("Guardar Código QR");
        btnGua.setContentAreaFilled(false);
        btnGua.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGua.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnGua2.png"))); // NOI18N
        btnGua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuaActionPerformed(evt);
            }
        });

        btnGen1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAbout1.png"))); // NOI18N
        btnGen1.setText("About");
        btnGen1.setToolTipText("About");
        btnGen1.setContentAreaFilled(false);
        btnGen1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGen1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGen1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAbout2.png"))); // NOI18N
        btnGen1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGen1ActionPerformed(evt);
            }
        });

        btnGen2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnInfo1.png"))); // NOI18N
        btnGen2.setText("Información");
        btnGen2.setToolTipText("Información");
        btnGen2.setBorderPainted(false);
        btnGen2.setContentAreaFilled(false);
        btnGen2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGen2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGen2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnInfo2.png"))); // NOI18N
        btnGen2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGen2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGua, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGen2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        primario.setBackground(new java.awt.Color(51, 51, 51));
        primario.setText("PRIMARIO");
        primario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primarioActionPerformed(evt);
            }
        });

        secundario.setBackground(new java.awt.Color(51, 51, 51));
        secundario.setText("SECUNDARIO");
        secundario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secundarioActionPerformed(evt);
            }
        });

        hora1.setForeground(new java.awt.Color(0, 0, 0));
        hora1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hora1.setText("COLORES");
        hora1.setColorDeSombra(new java.awt.Color(240, 240, 240));
        hora1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        texto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        texto.setForeground(new java.awt.Color(0, 102, 153));
        texto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(texto)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hora1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(hora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(primario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(secundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_cerrar1.png"))); // NOI18N
        cerrar.setToolTipText("Cerrar");
        cerrar.setContentAreaFilled(false);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_cerrar2.png"))); // NOI18N
        cerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        boton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_min2.png"))); // NOI18N
        boton3.setToolTipText("Minimizar");
        boton3.setContentAreaFilled(false);
        boton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn_min1.png"))); // NOI18N
        boton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoCod1.png"))); // NOI18N
        jLabel3.setToolTipText("Repara Ficheros RS");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelMetric1.setText("Generador QR...!!!");
        labelMetric1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(labelMetric1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void guardar() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Código QR");
        FileFilter filter = new FileNameExtensionFilter("QR Image", "PNG");
        fileChooser.addChoosableFileFilter(filter);
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File guardarQR = fileChooser.getSelectedFile();
            if (!guardarQR.toString().endsWith(".png")) {
                guardarQR = new File(fileChooser.getSelectedFile() + ".png");
            }
            try {
                ImageIO.write(iconoSys, "png", guardarQR);
                iconoSys = null;
                this.codigo.setIcon(null);
                this.texto.setText("");
            } catch (IOException ex) {
                System.err.println(ex.getMessage());
            }
        }
    }
    private void btnGuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuaActionPerformed
        if (iconoSys == null) {
            JOptionPane.showMessageDialog(this, "Debe generar un código QR\npara poder guardarlo.", "No genero código", 0,
                    new ImageIcon(getClass().getResource("/imagenes/msj_info.png")));
        } else {
            guardar();
        }
    }//GEN-LAST:event_btnGuaActionPerformed
    MyQRCreator qr = new MyQRCreator();
    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed
    int x, y;
    private boolean minimiza = false;
    BufferedImage iconoSys = null;
    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        this.setExtendedState(ICONIFIED);
        if (!minimiza) {
            minimiza = false;
        } else {
            minimiza = true;
        }
    }//GEN-LAST:event_boton3ActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnGen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGen1ActionPerformed
        new About(this, "", true).setVisible(true);
    }//GEN-LAST:event_btnGen1ActionPerformed

    private void btnGen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGen2ActionPerformed
        JOptionPane.showMessageDialog(this, "Básicamente el código no es mio, lo investigue y solo\n"
                + "le di un poco de diseño pero les recomiendo consultar\n"
                + "las siguientes páginas.\n\n"
                + "Fuentes investigadas y código obtenido de:\n"
                + "     http://www.jc-mouse.net/java/generador-de-codigos-qr-quick-response\n"
                + "     http://codejavu.blogspot.mx/2013/10/ejemplo-jcolorchooser.html\n"
                + "     https://www.youtube.com/watch?v=odFcjOvZsFg\n\n"
                + "Versión 1.1. Última actualización: 07/10/2016.", "Generador De Códigos QR...!!!", 0,
                new ImageIcon(getClass().getResource("/imagenes/about.png")));
    }//GEN-LAST:event_btnGen2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Timer tiempo = new Timer(100, new GenCodQR.hora());
        tiempo.start();
    }//GEN-LAST:event_formWindowOpened
    Color colorp = Color.white, colors = Color.black;
    private void primarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primarioActionPerformed
        if (iconoSys == null) {
            JOptionPane.showMessageDialog(this, "Debe generar un código QR\npara usar los colores.", "No genero código", 0,
                    new ImageIcon(getClass().getResource("/imagenes/msj_info.png")));
        } else {
            Color colorT = colorp;
            JColorChooser ventanaDeColores = new JColorChooser();
            colorp = ventanaDeColores.showDialog(this, "Seleccione un Color", Color.white);

            if (colorp != null) {
                iconoSys = new BufferedImage(345, 345, BufferedImage.TYPE_INT_RGB);
                iconoSys.createGraphics();
                Graphics2D graphics = (Graphics2D) iconoSys.getGraphics();
                graphics.setColor(colorp);
                graphics.fillRect(0, 0, 345, 345);
                graphics.setColor(colors);

                for (int i = 0; i < 345; i++) {
                    for (int j = 0; j < 345; j++) {
                        if (MyQRCreator.matrix.get(i, j)) {
                            graphics.fillRect(i, j, 1, 1);
                        }
                    }
                }

                ImageIcon QR = new ImageIcon(iconoSys);
                this.codigo.setIcon(QR);
            } else {
                colorp = colorT;
            }

        }
    }//GEN-LAST:event_primarioActionPerformed

    private void secundarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secundarioActionPerformed
        if (iconoSys == null) {
            JOptionPane.showMessageDialog(this, "Debe generar un código QR\npara usar los colores.", "No genero código", 0,
                    new ImageIcon(getClass().getResource("/imagenes/msj_info.png")));
        } else {
            Color colorT = colors;
            JColorChooser ventanaDeColores = new JColorChooser();
            colors = ventanaDeColores.showDialog(this, "Seleccione un Color", Color.black);

            if (colors != null) {

                iconoSys = new BufferedImage(345, 345, BufferedImage.TYPE_INT_RGB);
                iconoSys.createGraphics();
                Graphics2D graphics = (Graphics2D) iconoSys.getGraphics();
                graphics.setColor(colorp);
                graphics.fillRect(0, 0, 345, 345);
                graphics.setColor(colors);

                for (int i = 0; i < 345; i++) {
                    for (int j = 0; j < 345; j++) {
                        if (MyQRCreator.matrix.get(i, j)) {
                            graphics.fillRect(i, j, 1, 1);
                        }
                    }
                }

                ImageIcon QR = new ImageIcon(iconoSys);
                this.codigo.setIcon(QR);
            } else {
                colors = colorT;
            }
        }
    }//GEN-LAST:event_secundarioActionPerformed

    private void textoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoKeyReleased
        if (this.texto.getText().length() > 0) {
            iconoSys = qr.createQR(this.texto.getText(), 345, colorp, colors);
            ImageIcon QR = new ImageIcon(iconoSys);
            this.codigo.setIcon(QR);
            //            iconoSys = qr.createQR(this.texto.getText(), 500);
        } else {
            iconoSys = null;
            this.codigo.setIcon(null);
        }
    }//GEN-LAST:event_textoKeyReleased
    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Date sistemaHora = new Date();
            String pmAm = "hh:mm:ss a";
            SimpleDateFormat formato = new SimpleDateFormat(pmAm);
            Calendar now = Calendar.getInstance();
            hora.setText(String.format(formato.format(sistemaHora), now));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenCodQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenCodQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenCodQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenCodQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenCodQR().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton3;
    private javax.swing.JButton btnGen1;
    private javax.swing.JButton btnGen2;
    private javax.swing.JButton btnGua;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel codigo;
    private org.edisoncor.gui.label.LabelMetric hora;
    private org.edisoncor.gui.label.LabelMetric hora1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.button.ButtonSeven primario;
    private org.edisoncor.gui.button.ButtonSeven secundario;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
