package splas;

import principal.*;
import com.sun.awt.AWTUtilities;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JProgressBar;

/**
 *
 * @author Rojeru San
 */
public class Splash extends javax.swing.JFrame {

   Splash spl = this;
    public Splash() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoCod.png")).getImage());
        this.setLocationRelativeTo(this);
        AWTUtilities.setWindowOpaque(this, false);
        carga.setVisible(false);
        this.carga.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        startThread();
    }

    void startThread() {
        Thread hi = new Thread(new Runnable() {
            @Override
            public void run() {
                GenCodQR ven = new GenCodQR(spl);
                ven.setLocationRelativeTo(null);
                ven.setVisible(true);
                dispose();
            }
        });
        hi.start();
    }

    public JProgressBar getJProgressBar() {
        return carga;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen = new javax.swing.JLabel();
        carga = new org.edisoncor.gui.progressBar.ProgressBarRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splas/Splash.png"))); // NOI18N
        imagen.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        carga.setBackground(new java.awt.Color(255, 255, 255));
        carga.setForeground(new java.awt.Color(0, 153, 204));
        carga.setColorDeTexto(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(carga, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(imagen)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(carga, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.progressBar.ProgressBarRound carga;
    private javax.swing.JLabel imagen;
    // End of variables declaration//GEN-END:variables
}
